name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          check-latest: true
      - run: corepack enable
      - uses: bahmutov/npm-install@v1
      - run: yarn lint
      - run: yarn test:ci
      - run: yarn build
      - uses: codecov/codecov-action@v1
        with:
          file: ./packages/*/coverage/lcov.info
